/** Declaration file generated by dts-gen */
declare module 'buffer-map'{
export class BufferMap<TValue> {
    [Symbol.iterator](): Iterator;
    constructor(...args: any[]);

    clear(...args: any[]): void;

    delete(...args: any[]): void;

    entries(...args: any[]): void;

    forEach(...args: any[]): void;

    get(...args: any[]): TValue;

    has(...args: any[]): boolean;

    keys(...args: any[]): Buffer[];

    set(...args: any[]): void;

    toArray(...args: any[]): TValue[];

    toKeys(...args: any[]): Buffer[];

    toValues(...args: any[]): void;

    values(...args: any[]): void;

}

export class BufferSet {
    constructor(...args: any[]);

    add(...args: any[]): void;

    clear(...args: any[]): void;

    delete(...args: any[]): void;

    entries(...args: any[]): void;

    forEach(...args: any[]): void;

    has(...args: any[]): void;

    keys(...args: any[]): void;

    toArray(...args: any[]): void;

    toKeys(...args: any[]): void;

    toValues(...args: any[]): void;

    values(...args: any[]): void;

}

}