/** Declaration file generated by dts-gen */
declare module 'blgr' {

    export default blgr;

    declare class blgr {
        constructor(...args: any[]);

        close(...args: any[]): void;

        context(...args: any[]): blgr;

        debug(...args: any[]): void;

        error(...args: any[]): void;

        handleError(...args: any[]): void;

        info(...args: any[]): void;

        log(...args: any[]): void;

        logError(...args: any[]): void;

        memory(...args: any[]): void;

        memoryUsage(...args: any[]): void;

        open(...args: any[]): void;

        reopen(...args: any[]): void;

        retry(...args: any[]): void;

        set(...args: any[]): void;

        setFile(...args: any[]): void;

        setLevel(...args: any[]): void;

        spam(...args: any[]): void;

        truncate(...args: any[]): void;

        warning(...args: any[]): void;

        writeConsole(...args: any[]): void;

        writeStream(...args: any[]): void;

        static HAS_TTY: boolean;

        static MAX_FILE_SIZE: number;

        static levels: {
            DEBUG: number;
            ERROR: number;
            INFO: number;
            NONE: number;
            SPAM: number;
            WARNING: number;
        };

        static levelsByVal: string[];

        static prefixByVal: string[];

        static styles: string[];

    }

    declare namespace blgr {
        namespace global {
            const closed: boolean;

            const closing: boolean;

            const colors: boolean;

            const console: boolean;

            const contexts: {
            };

            const filename: any;

            const level: number;

            const shrink: boolean;

            const stream: any;

            function close(...args: any[]): void;

            function context(...args: any[]): void;

            function debug(...args: any[]): void;

            function error(...args: any[]): void;

            function handleError(...args: any[]): void;

            function info(...args: any[]): void;

            function log(...args: any[]): void;

            function logError(...args: any[]): void;

            function memory(...args: any[]): void;

            function memoryUsage(...args: any[]): void;

            function open(...args: any[]): void;

            function reopen(...args: any[]): void;

            function retry(...args: any[]): void;

            function set(...args: any[]): void;

            function setFile(...args: any[]): void;

            function setLevel(...args: any[]): void;

            function spam(...args: any[]): void;

            function truncate(...args: any[]): void;

            function warning(...args: any[]): void;

            function writeConsole(...args: any[]): void;

            function writeStream(...args: any[]): void;

        }

    }

}