/** Declaration file generated by dts-gen */
declare module "bufio" {
    export class BufferReader {
        constructor(...args: any[]);

        check(...args: any[]): void;

        createChecksum(...args: any[]): void;

        destroy(...args: any[]): void;

        end(...args: any[]): void;

        endData(...args: any[]): void;

        getSize(...args: any[]): void;

        left(...args: any[]): void;

        readBytes(...args: any[]): Buffer;

        readChild(...args: any[]): void;

        readDouble(...args: any[]): void;

        readDoubleBE(...args: any[]): void;

        readFloat(...args: any[]): void;

        readFloatBE(...args: any[]): void;

        readHash(...args: any[]): void;

        readI16(...args: any[]): void;

        readI16BE(...args: any[]): void;

        readI16BEBI(...args: any[]): void;

        readI16BI(...args: any[]): void;

        readI24(...args: any[]): void;

        readI24BE(...args: any[]): void;

        readI24BEBI(...args: any[]): void;

        readI24BI(...args: any[]): void;

        readI32(...args: any[]): void;

        readI32BE(...args: any[]): void;

        readI32BEBI(...args: any[]): void;

        readI32BI(...args: any[]): void;

        readI40(...args: any[]): void;

        readI40BE(...args: any[]): void;

        readI40BEBI(...args: any[]): void;

        readI40BI(...args: any[]): void;

        readI48BE(...args: any[]): void;

        readI48BEBI(...args: any[]): void;

        readI48BI(...args: any[]): void;

        readI56(...args: any[]): void;

        readI56BE(...args: any[]): void;

        readI56BEBI(...args: any[]): void;

        readI56BI(...args: any[]): void;

        readI64(...args: any[]): void;

        readI64BE(...args: any[]): void;

        readI64BEBI(...args: any[]): void;

        readI64BI(...args: any[]): void;

        readI8(...args: any[]): void;

        readI8BI(...args: any[]): void;

        readNullString(...args: any[]): void;

        readString(...args: any[]): void;

        readU16(...args: any[]): number;

        readU16BE(...args: any[]): number;

        readU16BEBI(...args: any[]): void;

        readU16BI(...args: any[]): void;

        readU24(...args: any[]): void;

        readU24BE(...args: any[]): void;

        readU24BEBI(...args: any[]): void;

        readU24BI(...args: any[]): void;

        readU32(...args: any[]): number;

        readU32BE(...args: any[]): number;

        readU32BEBI(...args: any[]): void;

        readU32BI(...args: any[]): void;

        readU40(...args: any[]): void;

        readU40BE(...args: any[]): void;

        readU40BEBI(...args: any[]): void;

        readU40BI(...args: any[]): void;

        readU48(...args: any[]): void;

        readU48BE(...args: any[]): void;

        readU48BI(...args: any[]): void;

        readU56(...args: any[]): void;

        readU56BE(...args: any[]): void;

        readU56BEBI(...args: any[]): void;

        readU56BI(...args: any[]): void;

        readU64(...args: any[]): void;

        readU64BE(...args: any[]): void;

        readU64BEBI(...args: any[]): void;

        readU64BI(...args: any[]): void;

        readU8(...args: any[]): number;

        readU8BI(...args: any[]): void;

        readVarBytes(...args: any[]): void;

        readVarString(...args: any[]): void;

        readVarint(...args: any[]): void;

        readVarint2(...args: any[]): void;

        readVarintBI(...args: any[]): void;

        seek(...args: any[]): void;

        start(...args: any[]): void;

        verifyChecksum(...args: any[]): void;

    }

    export class BufferWriter {
        constructor(...args: any[]);

        copy(...args: any[]): void;

        destroy(...args: any[]): void;

        fill(...args: any[]): void;

        getSize(...args: any[]): void;

        render(...args: any[]): Buffer;

        seek(...args: any[]): void;

        writeBytes(...args: any[]): void;

        writeChecksum(...args: any[]): void;

        writeDouble(...args: any[]): void;

        writeDoubleBE(...args: any[]): void;

        writeFloat(...args: any[]): void;

        writeFloatBE(...args: any[]): void;

        writeHash(...args: any[]): void;

        writeI16(...args: any[]): void;

        writeI16BE(...args: any[]): void;

        writeI16BEBI(...args: any[]): void;

        writeI16BI(...args: any[]): void;

        writeI24(...args: any[]): void;

        writeI24BE(...args: any[]): void;

        writeI24BEBI(...args: any[]): void;

        writeI24BI(...args: any[]): void;

        writeI32(...args: any[]): void;

        writeI32BE(...args: any[]): void;

        writeI32BEBI(...args: any[]): void;

        writeI32BI(...args: any[]): void;

        writeI40(...args: any[]): void;

        writeI40BE(...args: any[]): void;

        writeI40BEBI(...args: any[]): void;

        writeI40BI(...args: any[]): void;

        writeI48(...args: any[]): void;

        writeI48BE(...args: any[]): void;

        writeI48BEBI(...args: any[]): void;

        writeI48BI(...args: any[]): void;

        writeI56(...args: any[]): void;

        writeI56BE(...args: any[]): void;

        writeI56BEBI(...args: any[]): void;

        writeI56BI(...args: any[]): void;

        writeI64(...args: any[]): void;

        writeI64BE(...args: any[]): void;

        writeI64BEBI(...args: any[]): void;

        writeI64BI(...args: any[]): void;

        writeI8(...args: any[]): void;

        writeI8BI(...args: any[]): void;

        writeNullString(...args: any[]): void;

        writeString(...args: any[]): void;

        writeU16(...args: any[]): void;

        writeU16BE(...args: any[]): void;

        writeU16BEBI(...args: any[]): void;

        writeU16BI(...args: any[]): void;

        writeU24(...args: any[]): void;

        writeU24BE(...args: any[]): void;

        writeU24BEBI(...args: any[]): void;

        writeU24BI(...args: any[]): void;

        writeU32(...args: any[]): void;

        writeU32BE(...args: any[]): void;

        writeU32BEBI(...args: any[]): void;

        writeU40(...args: any[]): void;

        writeU40BE(...args: any[]): void;

        writeU40BEBI(...args: any[]): void;

        writeU40BI(...args: any[]): void;

        writeU48(...args: any[]): void;

        writeU48BE(...args: any[]): void;

        writeU48BEBI(...args: any[]): void;

        writeU48BI(...args: any[]): void;

        writeU56(...args: any[]): void;

        writeU56BE(...args: any[]): void;

        writeU56BEBI(...args: any[]): void;

        writeU56BI(...args: any[]): void;

        writeU64(...args: any[]): void;

        writeU64BE(...args: any[]): void;

        writeU64BEBI(...args: any[]): void;

        writeU64BI(...args: any[]): void;

        writeU8(...args: any[]): void;

        writeU8BI(...args: any[]): void;

        writeVarBytes(...args: any[]): void;

        writeVarString(...args: any[]): void;

        writeVarint(...args: any[]): void;

        writeVarint2(...args: any[]): void;

        writeVarintBI(...args: any[]): void;

    }

    export class StaticWriter {
        constructor(...args: any[]);

        check(...args: any[]): void;

        copy(...args: any[]): void;

        destroy(...args: any[]): void;

        fill(...args: any[]): void;

        getSize(...args: any[]): void;

        init(...args: any[]): void;

        render(...args: any[]): void;

        seek(...args: any[]): void;

        slice(...args: any[]): void;

        writeBytes(...args: any[]): void;

        writeChecksum(...args: any[]): void;

        writeDouble(...args: any[]): void;

        writeDoubleBE(...args: any[]): void;

        writeFloat(...args: any[]): void;

        writeFloatBE(...args: any[]): void;

        writeHash(...args: any[]): void;

        writeI16(...args: any[]): void;

        writeI16BE(...args: any[]): void;

        writeI16BEBI(...args: any[]): void;

        writeI16BI(...args: any[]): void;

        writeI24(...args: any[]): void;

        writeI24BE(...args: any[]): void;

        writeI24BEBI(...args: any[]): void;

        writeI24BI(...args: any[]): void;

        writeI32(...args: any[]): void;

        writeI32BE(...args: any[]): void;

        writeI32BEBI(...args: any[]): void;

        writeI32BI(...args: any[]): void;

        writeI40(...args: any[]): void;

        writeI40BE(...args: any[]): void;

        writeI40BEBI(...args: any[]): void;

        writeI40BI(...args: any[]): void;

        writeI48(...args: any[]): void;

        writeI48BE(...args: any[]): void;

        writeI48BEBI(...args: any[]): void;

        writeI48BI(...args: any[]): void;

        writeI56(...args: any[]): void;

        writeI56BE(...args: any[]): void;

        writeI56BEBI(...args: any[]): void;

        writeI56BI(...args: any[]): void;

        writeI64(...args: any[]): void;

        writeI64BE(...args: any[]): void;

        writeI64BEBI(...args: any[]): void;

        writeI64BI(...args: any[]): void;

        writeI8(...args: any[]): void;

        writeI8BI(...args: any[]): void;

        writeNullString(...args: any[]): void;

        writeString(...args: any[]): void;

        writeU16(...args: any[]): void;

        writeU16BE(...args: any[]): void;

        writeU16BEBI(...args: any[]): void;

        writeU16BI(...args: any[]): void;

        writeU24(...args: any[]): void;

        writeU24BE(...args: any[]): void;

        writeU24BEBI(...args: any[]): void;

        writeU24BI(...args: any[]): void;

        writeU32(...args: any[]): void;

        writeU32BE(...args: any[]): void;

        writeU32BEBI(...args: any[]): void;

        writeU32BI(...args: any[]): void;

        writeU40(...args: any[]): void;

        writeU40BE(...args: any[]): void;

        writeU40BEBI(...args: any[]): void;

        writeU40BI(...args: any[]): void;

        writeU48(...args: any[]): void;

        writeU48BE(...args: any[]): void;

        writeU48BEBI(...args: any[]): void;

        writeU48BI(...args: any[]): void;

        writeU56(...args: any[]): void;

        writeU56BE(...args: any[]): void;

        writeU56BEBI(...args: any[]): void;

        writeU56BI(...args: any[]): void;

        writeU64(...args: any[]): void;

        writeU64BE(...args: any[]): void;

        writeU64BEBI(...args: any[]): void;

        writeU64BI(...args: any[]): void;

        writeU8(...args: any[]): void;

        writeU8BI(...args: any[]): void;

        writeVarBytes(...args: any[]): void;

        writeVarString(...args: any[]): void;

        writeVarint(...args: any[]): void;

        writeVarint2(...args: any[]): void;

        writeVarintBI(...args: any[]): void;

        static pool(...args: any[]): void;

    }

    export class Struct {
        constructor(...args: any[]);

        clone(...args: any[]): void;

        decode(...args: any[]): void;

        encode(...args: any[]): void;

        format(...args: any[]): void;

        from(...args: any[]): void;

        fromBase64(...args: any[]): void;

        fromHex(...args: any[]): void;

        fromJSON(...args: any[]): void;

        fromOptions(...args: any[]): void;

        fromRaw(...args: any[]): void;

        fromReader(...args: any[]): void;

        fromString(...args: any[]): void;

        getJSON(...args: any[]): void;

        getSize(...args: any[]): void;

        inject(...args: any[]): void;

        read(...args: any[]): void;

        toBase64(...args: any[]): void;

        toHex(...args: any[]): void;

        toJSON(...args: any[]): void;

        toRaw(...args: any[]): void;

        toString(...args: any[]): void;

        toWriter(...args: any[]): void;

        write(...args: any[]): void;

        static decode(...args: any[]): void;

        static from(...args: any[]): void;

        static fromBase64(...args: any[]): void;

        static fromHex(...args: any[]): void;

        static fromJSON(...args: any[]): void;

        static fromOptions(...args: any[]): void;

        static fromRaw(...args: any[]): void;

        static fromReader(...args: any[]): void;

        static fromString(...args: any[]): void;

        static read(...args: any[]): void;

    }

    export const custom: {
        custom: any;
    };

    export function EncodingError(...args: any[]): void;

    export function concat(a: any, b: any): any;

    export function copy(data: any): any;

    export function pool(size: any): any;

    export function read(data: any, zeroCopy?: any): any;

    export function readBytes(data: any, off: any, size: any): any;

    export function readDouble(data: any, off: any): any;

    export function readDoubleBE(data: any, off: any): any;

    export function readFloat(data: any, off: any): any;

    export function readFloatBE(data: any, off: any): any;

    export function readI(data: any, off: any, len: any): any;

    export function readI16(data: any, off: any): any;

    export function readI16BE(data: any, off: any): any;

    export function readI24(data: any, off: any): any;

    export function readI24BE(data: any, off: any): any;

    export function readI32(data: any, off: any): any;

    export function readI32BE(data: any, off: any): any;

    export function readI40(data: any, off: any): any;

    export function readI40BE(data: any, off: any): any;

    export function readI48(data: any, off: any): any;

    export function readI48BE(data: any, off: any): any;

    export function readI56(data: any, off: any): any;

    export function readI56BE(data: any, off: any): any;

    export function readI64(data: any, off: any): any;

    export function readI64BE(data: any, off: any): any;

    export function readI8(data: any, off: any): any;

    export function readIBE(data: any, off: any, len: any): any;

    export function readString(data: any, off: any, size: any, enc: any): any;

    export function readU(data: any, off: any, len: any): any;

    export function readU16(data: any, off: any): any;

    export function readU16BE(data: any, off: any): any;

    export function readU24(data: any, off: any): any;

    export function readU24BE(data: any, off: any): any;

    export function readU32(data: any, off: any): any;

    export function readU32BE(data: any, off: any): any;

    export function readU40(data: any, off: any): any;

    export function readU40BE(data: any, off: any): any;

    export function readU48(data: any, off: any): any;

    export function readU48BE(data: any, off: any): any;

    export function readU56(data: any, off: any): any;

    export function readU56BE(data: any, off: any): any;

    export function readU64(data: any, off: any): any;

    export function readU64BE(data: any, off: any): any;

    export function readU8(data: any, off: any): any;

    export function readUBE(data: any, off: any, len: any): any;

    export function readVarint(data: any, off: any): any;

    export function readVarint2(data: any, off: any): any;

    export function realloc(data: any, size: any): any;

    export function sizeVarBytes(data: any): any;

    export function sizeVarString(str: any, enc: any): any;

    export function sizeVarint(num: any): any;

    export function sizeVarint2(num: any): any;

    export function sizeVarlen(len: any): any;

    export function sliceBytes(data: any, off: any, size: any): any;

    export function write(size?: any): any;

    export function writeBytes(data: any, value: any, off: any): any;

    export function writeDouble(data: any, num: any, off: any): any;

    export function writeDoubleBE(data: any, num: any, off: any): any;

    export function writeFloat(data: any, num: any, off: any): any;

    export function writeFloatBE(data: any, num: any, off: any): any;

    export function writeI(data: any, num: any, off: any, len: any): any;

    export function writeI16(data: any, num: any, off: any): any;

    export function writeI16BE(data: any, num: any, off: any): any;

    export function writeI24(data: any, num: any, off: any): any;

    export function writeI24BE(data: any, num: any, off: any): any;

    export function writeI32(data: any, num: any, off: any): any;

    export function writeI32BE(data: any, num: any, off: any): any;

    export function writeI40(data: any, num: any, off: any): any;

    export function writeI40BE(data: any, num: any, off: any): any;

    export function writeI48(data: any, num: any, off: any): any;

    export function writeI48BE(data: any, num: any, off: any): any;

    export function writeI56(data: any, num: any, off: any): any;

    export function writeI56BE(data: any, num: any, off: any): any;

    export function writeI64(data: any, num: any, off: any): any;

    export function writeI64BE(data: any, num: any, off: any): any;

    export function writeI8(data: any, num: any, off: any): any;

    export function writeIBE(data: any, num: any, off: any, len: any): any;

    export function writeString(data: any, str: any, off: any, enc: any): any;

    export function writeU(data: any, num: any, off: any, len: any): any;

    export function writeU16(data: any, num: any, off: any): any;

    export function writeU16BE(data: any, num: any, off: any): any;

    export function writeU24(data: any, num: any, off: any): any;

    export function writeU24BE(data: any, num: any, off: any): any;

    export function writeU32(data: any, num: any, off: any): any;

    export function writeU32BE(data: any, num: any, off: any): any;

    export function writeU40(data: any, num: any, off: any): any;

    export function writeU40BE(data: any, num: any, off: any): any;

    export function writeU48(data: any, num: any, off: any): any;

    export function writeU48BE(data: any, num: any, off: any): any;

    export function writeU56(data: any, num: any, off: any): any;

    export function writeU56BE(data: any, num: any, off: any): any;

    export function writeU64(data: any, num: any, off: any): any;

    export function writeU64BE(data: any, num: any, off: any): any;

    export function writeU8(data: any, num: any, off: any): any;

    export function writeUBE(data: any, num: any, off: any, len: any): any;

    export function writeVarint(data: any, num: any, off: any): any;

    export function writeVarint2(data: any, num: any, off: any): any;

    export namespace EncodingError {
        const stackTraceLimit: number;

        function captureStackTrace(p0: any, p1: any): any;

    }

    export namespace encoding {
        function concat(a: any, b: any): any;

        function copy(data: any): any;

        function readBytes(data: any, off: any, size: any): any;

        function readDouble(data: any, off: any): any;

        function readDoubleBE(data: any, off: any): any;

        function readFloat(data: any, off: any): any;

        function readFloatBE(data: any, off: any): any;

        function readI(data: any, off: any, len: any): any;

        function readI16(data: any, off: any): any;

        function readI16BE(data: any, off: any): any;

        function readI16BEBI(data: any, off: any): any;

        function readI16BI(data: any, off: any): any;

        function readI24(data: any, off: any): any;

        function readI24BE(data: any, off: any): any;

        function readI24BEBI(data: any, off: any): any;

        function readI24BI(data: any, off: any): any;

        function readI32(data: any, off: any): any;

        function readI32BE(data: any, off: any): any;

        function readI32BEBI(data: any, off: any): any;

        function readI32BI(data: any, off: any): any;

        function readI40(data: any, off: any): any;

        function readI40BE(data: any, off: any): any;

        function readI40BEBI(data: any, off: any): any;

        function readI40BI(data: any, off: any): any;

        function readI48(data: any, off: any): any;

        function readI48BE(data: any, off: any): any;

        function readI48BEBI(data: any, off: any): any;

        function readI48BI(data: any, off: any): any;

        function readI56(data: any, off: any): any;

        function readI56BE(data: any, off: any): any;

        function readI56BEBI(data: any, off: any): any;

        function readI56BI(data: any, off: any): any;

        function readI64(data: any, off: any): any;

        function readI64BE(data: any, off: any): any;

        function readI64BEBI(data: any, off: any): any;

        function readI64BI(data: any, off: any): any;

        function readI8(data: any, off: any): any;

        function readI8BI(data: any, off: any): any;

        function readIBE(data: any, off: any, len: any): any;

        function readIBEBI(data: any, off: any, len: any): any;

        function readIBI(data: any, off: any, len: any): any;

        function readString(data: any, off: any, size: any, enc: any): any;

        function readU(data: any, off: any, len: any): any;

        function readU16(data: any, off: any): any;

        function readU16BE(data: any, off: any): any;

        function readU16BEBI(data: any, off: any): any;

        function readU16BI(data: any, off: any): any;

        function readU24(data: any, off: any): any;

        function readU24BE(data: any, off: any): any;

        function readU24BEBI(data: any, off: any): any;

        function readU24BI(data: any, off: any): any;

        function readU32(data: any, off: any): any;

        function readU32BE(data: any, off: any): any;

        function readU32BEBI(data: any, off: any): any;

        function readU32BI(data: any, off: any): any;

        function readU40(data: any, off: any): any;

        function readU40BE(data: any, off: any): any;

        function readU40BEBI(data: any, off: any): any;

        function readU40BI(data: any, off: any): any;

        function readU48(data: any, off: any): any;

        function readU48BE(data: any, off: any): any;

        function readU48BEBI(data: any, off: any): any;

        function readU48BI(data: any, off: any): any;

        function readU56(data: any, off: any): any;

        function readU56BE(data: any, off: any): any;

        function readU56BEBI(data: any, off: any): any;

        function readU56BI(data: any, off: any): any;

        function readU64(data: any, off: any): any;

        function readU64BE(data: any, off: any): any;

        function readU64BEBI(data: any, off: any): any;

        function readU64BI(data: any, off: any): any;

        function readU8(data: any, off: any): any;

        function readU8BI(data: any, off: any): any;

        function readUBE(data: any, off: any, len: any): any;

        function readUBEBI(data: any, off: any, len: any): any;

        function readUBI(data: any, off: any, len: any): any;

        function readVarint(data: any, off: any): any;

        function readVarint2(data: any, off: any): any;

        function readVarintBI(data: any, off: any): any;

        function realloc(data: any, size: any): any;

        function sizeVarBytes(data: any): any;

        function sizeVarString(str: any, enc: any): any;

        function sizeVarint(num: any): any;

        function sizeVarint2(num: any): any;

        function sizeVarintBI(num: any): any;

        function sizeVarlen(len: any): any;

        function sliceBytes(data: any, off: any, size: any): any;

        function writeBytes(data: any, value: any, off: any): any;

        function writeDouble(dst: any, num: any, off: any): any;

        function writeDoubleBE(dst: any, num: any, off: any): any;

        function writeFloat(dst: any, num: any, off: any): any;

        function writeFloatBE(dst: any, num: any, off: any): any;

        function writeI(dst: any, num: any, off: any, len: any): any;

        function writeI16(dst: any, num: any, off: any): any;

        function writeI16BE(dst: any, num: any, off: any): any;

        function writeI16BEBI(dst: any, num: any, off: any): any;

        function writeI16BI(dst: any, num: any, off: any): any;

        function writeI24(dst: any, num: any, off: any): any;

        function writeI24BE(dst: any, num: any, off: any): any;

        function writeI24BEBI(dst: any, num: any, off: any): any;

        function writeI24BI(dst: any, num: any, off: any): any;

        function writeI32(dst: any, num: any, off: any): any;

        function writeI32BE(dst: any, num: any, off: any): any;

        function writeI32BEBI(dst: any, num: any, off: any): any;

        function writeI32BI(dst: any, num: any, off: any): any;

        function writeI40(dst: any, num: any, off: any): any;

        function writeI40BE(dst: any, num: any, off: any): any;

        function writeI40BEBI(dst: any, num: any, off: any): any;

        function writeI40BI(dst: any, num: any, off: any): any;

        function writeI48(dst: any, num: any, off: any): any;

        function writeI48BE(dst: any, num: any, off: any): any;

        function writeI48BEBI(dst: any, num: any, off: any): any;

        function writeI48BI(dst: any, num: any, off: any): any;

        function writeI56(dst: any, num: any, off: any): any;

        function writeI56BE(dst: any, num: any, off: any): any;

        function writeI56BEBI(dst: any, num: any, off: any): any;

        function writeI56BI(dst: any, num: any, off: any): any;

        function writeI64(dst: any, num: any, off: any): any;

        function writeI64BE(dst: any, num: any, off: any): any;

        function writeI64BEBI(dst: any, num: any, off: any): any;

        function writeI64BI(dst: any, num: any, off: any): any;

        function writeI8(dst: any, num: any, off: any): any;

        function writeI8BI(dst: any, num: any, off: any): any;

        function writeIBE(dst: any, num: any, off: any, len: any): any;

        function writeIBEBI(dst: any, num: any, off: any, len: any): any;

        function writeIBI(dst: any, num: any, off: any, len: any): any;

        function writeString(data: any, str: any, off: any, enc: any): any;

        function writeU(dst: any, num: any, off: any, len: any): any;

        function writeU16(dst: any, num: any, off: any): any;

        function writeU16BE(dst: any, num: any, off: any): any;

        function writeU16BEBI(dst: any, num: any, off: any): any;

        function writeU16BI(dst: any, num: any, off: any): any;

        function writeU24(dst: any, num: any, off: any): any;

        function writeU24BE(dst: any, num: any, off: any): any;

        function writeU24BEBI(dst: any, num: any, off: any): any;

        function writeU24BI(dst: any, num: any, off: any): any;

        function writeU32(dst: any, num: any, off: any): any;

        function writeU32BE(dst: any, num: any, off: any): any;

        function writeU32BEBI(dst: any, num: any, off: any): any;

        function writeU32BI(dst: any, num: any, off: any): any;

        function writeU40(dst: any, num: any, off: any): any;

        function writeU40BE(dst: any, num: any, off: any): any;

        function writeU40BEBI(dst: any, num: any, off: any): any;

        function writeU40BI(dst: any, num: any, off: any): any;

        function writeU48(dst: any, num: any, off: any): any;

        function writeU48BE(dst: any, num: any, off: any): any;

        function writeU48BEBI(dst: any, num: any, off: any): any;

        function writeU48BI(dst: any, num: any, off: any): any;

        function writeU56(dst: any, num: any, off: any): any;

        function writeU56BE(dst: any, num: any, off: any): any;

        function writeU56BEBI(dst: any, num: any, off: any): any;

        function writeU56BI(dst: any, num: any, off: any): any;

        function writeU64(dst: any, num: any, off: any): any;

        function writeU64BE(dst: any, num: any, off: any): any;

        function writeU64BEBI(dst: any, num: any, off: any): any;

        function writeU64BI(dst: any, num: any, off: any): any;

        function writeU8(dst: any, num: any, off: any): any;

        function writeU8BI(dst: any, num: any, off: any): any;

        function writeUBE(dst: any, num: any, off: any, len: any): any;

        function writeUBEBI(dst: any, num: any, off: any, len: any): any;

        function writeUBI(dst: any, num: any, off: any, len: any): any;

        function writeVarint(dst: any, num: any, off: any): any;

        function writeVarint2(dst: any, num: any, off: any): any;

        function writeVarintBI(dst: any, num: any, off: any): any;

    }

}
